module.exports = {
  apps: [
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 1",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 2",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 2",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 3",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 4",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 5",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 6",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 7",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 8",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 9",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 10",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 11",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 12",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 13",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 14",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 15",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 16",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 17",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 18",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 19",
    },
    {
      name: "Get Dataset",
      script: "./hn_datasets/get_dataset.py",
      interpreter: "/usr/bin/python3.9",
      instances: 1,
      args: "20 20",
    },
    {
      name: "app1",
      script: "./hn_datasets/ingest.py",
      interpreter: "/usr/bin/python3.9",
      instances: 30,
    },
  ],
};
